# frozen_string_literal: true

# RuboCop configuration
# Following Ruby community standards and best practices

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"

# Style preferences
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Metrics - following Sandi Metz rules where practical
Metrics/MethodLength:
  Max: 10
  Exclude:
    - "config/**/*"
    - "bin/**/*"
    - "examples/**/*"
    - "lib/profile_generator/interactors/generate_profile.rb"
    - "lib/profile_generator/services/anthropic_client.rb"
    - "lib/profile_generator/services/content_formatter.rb"
    - "lib/profile_generator/services/async_profile_generator.rb"

Metrics/ClassLength:
  Max: 100
  Exclude:
    - "app/application.rb"
    - "lib/profile_generator/interactors/generate_profile.rb"
    - "lib/profile_generator/services/anthropic_client.rb"
    - "lib/profile_generator/services/content_formatter.rb"

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "app/application.rb"
    - "bin/**/*"
    - "examples/**/*"
    - "lib/profile_generator/interactors/generate_profile.rb"
    - "lib/profile_generator/services/anthropic_client.rb"
    - "lib/profile_generator/services/content_formatter.rb"

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - "lib/profile_generator/services/anthropic_client.rb"

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - "lib/profile_generator/services/anthropic_client.rb"

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "config.ru"
    - "spec/**/*"

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - "# rubocop"
  Exclude:
    - "Gemfile"
    - "bin/**/*"

# Naming
Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
